### ISSUE TITLE
Command modifier on `arnew` conflicts with Alfred template choices

### ISSUE THREAD

**Issue by wduquette** [pryley/alfred-the-archive#4]
When I use `arnew`, Alfred presents me with a list of templates.  I have several at present.  I can select them via the keyboard by pressing Command-2, Command-3, etc.  If I do that, the Command-modifier is lost so far as your script is concerned.  Maybe use a different modifier for toggling the presence/absence of the Zettel ID?  Or maybe just make it a configuration flag, instead of something to toggle?

I'm not sure what the best thing to do here is, but it's really quite nice to just be able to press Command-3 and get that template.

**Comment by pryley** [comment]
⌘+NUM is a built-in Alfred action modifier to action result items. Since Alfred's action modifier _cannot be used in conjunction with other keys_, there is no real solution for this.

You could always change the modifier key, but this still would not provide you the ability to use the Workflow modifier key (which toggles the Zettel ID) together with the Alfred ⌘+NUM modifier key as this is is an Alfred limitation. 

![image](https://user-images.githubusercontent.com/134939/88139017-7c688d80-cbb4-11ea-8ec8-a974e8c4b800.png)

**Comment by wduquette** [comment]
Got it.  Thanks for explaining.
